version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./src/web/templates:/usr/share/nginx/html
      - ./src/web/static:/usr/share/nginx/html/static
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
