services:
  api:
    build:
      context: .
      network: host
    network_mode: host
    volumes:
      - .:/app
    restart: always
  web:
    image: nginx:alpine
    network_mode: host
    volumes:
      - ./src/web/templates:/usr/share/nginx/html
      - ./src/web/static:/usr/share/nginx/html/static
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
