services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    network_mode: host
    volumes:
      - .:/app
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
  web:
    image: nginx:alpine
    network_mode: host
    volumes:
      - ./src/web/templates:/usr/share/nginx/html
      - ./src/web/static:/usr/share/nginx/html/static
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
